# Generated by Django 4.1.5 on 2023-02-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('NA', 'NA'), ('in_process', 'in_process'), ('selected', 'selected'), ('failed', 'failed')], default='NA', max_length=255),
        ),
    ]
